spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs544-lab5?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: P@ss12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: lab8
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: ERROR
    org:
      springframework: ERROR