application:
  name: config
  # Version
  version: 1.0.0

  server:
    # Server URL
    url: http://myurl.com
    # Server name
    name: myServer
  user:
    # User firstname
    firstname: FirstName
    # User lastname
    lastname: LastName
    username: username
    password: password
  countries: United States, Canada, United Kingdom, Australia, Germany
