spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs544-examples?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: P@ss12345
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: ERROR
    org:
      springframework: ERROR

